##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Copyright © dev-cetera.com & contributors.
##
## The use of this source code is governed by an MIT-style license described in
## the LICENSE file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_dart_models
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_generate_dart_models
funding:
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.buymeacoffee.com/dev_cetera
description: A tool for generating data models and classes from annotations, offering greater flexibility than json_serializable or freezed.
version: 0.14.2
topics:
  - build-runner
  - cli
  - codegen
  - freezed
  - json-serializable

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  google_generative_ai: ^0.4.7
  path: ^1.9.1

  df_collection: ^0.9.8
  df_config: ^0.7.5
  df_gen_core: ^0.7.0
  df_generate_dart_models_core: ^0.9.22
  df_log: ^0.3.20
  df_string: ^0.2.10
  df_type: ^0.14.2

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

## -----------------------------------------------------------------------------

executables:
  --models: df_generate_dart_models
  --models-min: df_generate_dart_models_min
  --models-gemeni: df_generate_dart_models_gemeni
  df_generate_dart_models: df_generate_dart_models
  df_generate_dart_models_min: df_generate_dart_models_min
  df_generate_dart_models_gemeni: df_generate_dart_models_gemeni

